import type { APIRoute } from 'astro';
import { SITE } from '../lib/seo';
import manifest from '../content/llms-manifest.json';

/**
 * llms.txt — auto-built AI-readable index of the docs site.
 *
 * Convention: https://llmstxt.org/. Format is intentionally minimal so any
 * agent can ingest the site without scraping HTML. The shape here mirrors
 * slotplate's: H1 + tagline blockquote + sectioned bullets, one per page.
 *
 * Content is generated by docs/scripts/build-llms.mjs during prebuild — DO
 * NOT edit the manifest by hand. Add new docs pages, run the build, the
 * manifest catches up automatically.
 */

interface SectionItem {
  href: string;
  title: string;
  description: string;
}

interface Section {
  id: string;
  label: string;
  items: SectionItem[];
}

interface ApiEntry {
  name: string;
  kind: string;
  summary: string;
  href: string;
}

interface ChangelogEntry {
  id: string;
  bump: string;
  title: string;
}

interface Manifest {
  generatedAt?: string;
  sections: Section[];
  api: ApiEntry[];
  changelog: ChangelogEntry[];
}

const TAGLINE =
  'Wwise-grade web audio in a tiny ESM package — lazy AudioContext, mixer buses, sidechain ducking, snapshots, sprites, codec-aware loading.';

function bullet(href: string, title: string, description: string): string {
  const url = new URL(href, SITE.url).toString();
  return description ? `- [${title}](${url}): ${description}` : `- [${title}](${url})`;
}

function render(m: Manifest): string {
  const lines: string[] = [];
  lines.push(`# ${SITE.name}`);
  lines.push('');
  lines.push(`> ${TAGLINE}`);
  lines.push('');

  for (const section of m.sections) {
    if (section.items.length === 0) continue;
    lines.push(`## ${section.label}`);
    lines.push('');
    for (const item of section.items) {
      lines.push(bullet(item.href, item.title, item.description));
    }
    lines.push('');
  }

  if (m.api.length > 0) {
    lines.push('## API');
    lines.push('');
    // Group by kind so Classes / Functions / Interfaces cluster together.
    const byKind = new Map<string, ApiEntry[]>();
    for (const entry of m.api) {
      const k = entry.kind || 'Symbol';
      if (!byKind.has(k)) byKind.set(k, []);
      byKind.get(k)!.push(entry);
    }
    const kinds = Array.from(byKind.keys()).sort();
    for (const kind of kinds) {
      lines.push(`### ${kind}`);
      lines.push('');
      for (const entry of byKind.get(kind)!) {
        lines.push(bullet(entry.href, entry.name, entry.summary));
      }
      lines.push('');
    }
  }

  if (m.changelog.length > 0) {
    lines.push('## Changelog');
    lines.push('');
    for (const entry of m.changelog) {
      const url = new URL(`/changelog/#${entry.id}`, SITE.url).toString();
      lines.push(`- [${entry.title}](${url}) — ${entry.bump}`);
    }
    lines.push('');
  }

  if (m.generatedAt) {
    lines.push(`<!-- generated ${m.generatedAt} by docs/scripts/build-llms.mjs -->`);
    lines.push('');
  }
  return lines.join('\n');
}

export const GET: APIRoute = () => {
  return new Response(render(manifest as Manifest), {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};
